# Inserts a blank line between shell prompts
add_newline = false

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ— â¯](bold red)"

[jobs]
number_threshold = 1
symbol = "ğŸ’¼"

[package]
disabled = false

[directory]
home_symbol = "ğŸ "

[line_break]
disabled = true

[git_status]
disabled = false

[time]
disabled = false
use_12hr = true
format = " [$time]($style) "
time_format = "%H:%M"
