format = """
[â–‘â–’â–“](#13890b)\
[ ğŸª´](bg:#13890b fg:#090c0c)\
[î‚´](bg:#41b70e fg:#13890b)\
$directory\
[î‚´](fg:#41b70e bg:#394260)\
$git_branch\
$git_status\
[î‚´](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
[î‚´](fg:#212736 bg:#1d2230)\
$time\
[î‚´ ](fg:#1d2230)\
\n$character"""

add_newline = false

[line_break]
disabled = true

[directory]
style = "fg:#e3e5e5 bg:#41b70e"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "ğŸ“"

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#41b70e bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#41b70e bg:#394260)]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#41b70e bg:#212736)]($style)'

[rust]
symbol = "î¨"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#41b70e bg:#212736)]($style)'

[golang]
symbol = "ï³‘"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#41b70e bg:#212736)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#41b70e bg:#212736)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[ ïº $time ](fg:#a0a9cb bg:#1d2230)]($style)'
