# Inserts a blank line between shell prompts
add_newline = false

[character]
success_symbol = "[ğŸŒµ â¯](bold green)"
error_symbol = "[âœ— â¯](bold red)"
vicmd_symbol = "[V](bold green) "

[package]
disabled = false

[directory]
home_symbol = "ğŸ "

[line_break]
disabled = true

[git_status]
disabled = false
