[line_break]
disabled = true

add_newline = false

[directory]
truncation_length = 3
truncation_symbol = "ğŸ“"

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[time]
disabled = false
time_format = "%R"
style = "bg:#b57614"
format = 'ïº $time '

[battery]
charging_symbol = 'ğŸ”Œ '
discharging_symbol = 'âš¡ï¸ '
full_symbol = 'ğŸ”‹ '

[[battery.display]]
threshold = 100
