add_newline = false

[directory]
truncation_length = 8
truncation_symbol = 'ğŸ“ '


[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[ ğŸŒµ $time ]($style)'
