add_newline = false

[directory]
truncation_length = 8
truncation_symbol = 'ğŸ“ '


[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[time]
disabled = true
# format = '[ ğŸŒµ ]($style)'
